// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  description: dynamic(() => import('./Description')),
  photo: dynamic(() => import('./Photo')),
  rich_text: dynamic(() => import('./RichText')),
  gallery: dynamic(() => import('./Gallery')),
  gallery_item: dynamic(() => import('./GalleryItem')),
  text: dynamic(() => import('./Text')),
};
